### ISSUE TITLE
forwarding of loadIncremental.log to stackato does not seem to work

### ISSUE THREAD

**Issue by cgroeschel** [voxgen/pentaho4-pdi-buildpack#1]
the logging within container works ok and can be tail'ed normally but is not forwarded to stackato.

manifest.yml used:

applications:
- name: dpd-ng-pdi
  buildpack: https://github.com/voxgen/pentaho4-pdi-buildpack.git
  memory: 1G
  disk: 1G
  url: []
  stackato:
    hooks:
      post-staging:
      - touch $HOME/log/loadIncremental.log 
    env:
      STACKATO_LOG_FILES: loadincremental=$HOME/log/loadIncremental.log:$STACKATO_LOG_FILES
    cron:
      - "*/1 * * * * $HOME/scripts/loadIncremental.sh >> $HOME/log/loadIncremental.log"   

Straight after staging this message pops up:
2015-10-09T14:59:07+0200 stackato[apptail.0]: WARN -- Ignoring missing/inaccessible path /home/stackato/log/loadIncremental.log

The PDI app is RUNNING ok otherwise.

**Comment by mabeveridge** [comment]
The STACKATO_LOG_FILES  environment variable is not set correctly in the manifest.yml. Looking at the error message you can see that the value '$HOME/log/loadIncremental.log' is resolving to '/home/stackato/log/loadIncremental.log' but the log file is actually '/home/stackato/app/log/loadIncremental.log' - i.e. under the 'app' directory.

I'm not sure why the $HOME variable is interpreted this way when used in STACKATO_LOG_FILES, especially as it seems to resolve correctly to the app root when used in post-staging hooks. The Stackato documentation on logging refers to a STACKATO_APP_ROOT variable which should perhaps be used instead for this purpose. Alternatively, you can use the path given in the 'Example Manifest File' section of the README.md for this buildpack - namely:

STACKATO_LOG_FILES: incremental=app/log/loadIncremental.log:$STACKATO_LOG_FILES

I've found that this works correctly.
